	;ATASM
	;
	;HELLO SCREEN
	;
	*=$3000
	JMP INIT
	;
	SDMCTL=$022F; 0 TURNS ANTIC OFF ; 22 TURNS ANTIC BACK ON (SHADOW, DMA CONTROL)
	;
	SDLSTL=$0230; -STORES LOW BYTE OF DISPLAY LIST LOCATION (SHADOW, DISPLAY LIST POINTER LOW)
	SDLSTH=$0231; -STORES HIGH BYTE OF DISPLAY LIST LOCATION (SHADOW, DISPLAY LIST POINTER HIGH)
	;
	COLOR0=$02C4; OS COLOR REGISTERS
	COLOR1=$02C5
	COLOR2=$02C6
	COLOR3=$02C7
	COLOR4=$02C8
	;
	;DISPLAY LIST DATA
	;
	START
	;
	LINE1 .SBYTE "     PRESENTING    "
	LINE2 .SBYTE "   JOE IS A MASSIVE  "
	LINE3 .SBYTE "         DICK!     "
	;
	LINE4 .SBYTE "   PLEASE STAND BY   "
	;
	;DISPLAY LIST
	;
	HLIST
		.BYTE $70,$70,$70; 3 BLANK LINES
		.BYTE $70, $70, $70, $70,$70; MORE BLANK LINES
		.BYTE $46; LSM, ANTIC MODE 6 (BASIC MODE 2) - The 4 indicates LMS instruction, the 6 indicates mode 6
		.WORD LINE1; (TEXT LINE: "PRESENTING...") - this stores 2 bytes of the line1 sbyte in the display list
		.BYTE $70,$70,$70,$70,$47; LMS, ANTIC MODE 7
		.WORD LINE2; (TEXT LINE: "THE BIG PROGRAM")this stores 2 bytes of the line2 sbyte in the display list
		.BYTE $70,$47; (LMS, ANTIC MODE 2 [GR.0])
		.WORD LINE3;(TEXT LINE: "By [Your Name]") this stores 3 bytes of the line3 sbyte in the display list
		.BYTE $70,$70,$70,$70,$46;LMS, ANTIC MODE 6
		.WORD LINE4; (TEXT LINE: "PLEASE STAND BY") this stores 2 bytes of the line4 sbyte in the display list
		.BYTE $70,$70,$70,$70,$70; 5 BLANK LINES
		.BYTE $41; JVB INSTRUCTION - ALL DISPLAY LISTS MUST END WITH JVB (jump and wait for VBI)
		.WORD HLIST; TO JUMP BACK TO START OF LIST - JUMPS BACK TO BEGINNNING OF DISPLAY LIST
	;
	;RUN PROGRAM
	;
	INIT NOP; SWITCHING COLOR REGISTERS FOR NICELY COLORED DISPLAY
	LDA #$FF
	STA COLOR0
	LDA #$FF
	STA COLOR1
	STA COLOR2
	STA COLOR3
	LDA #$0
	STA COLOR4
	; NOW WE'LL RUN THE PROGRAM
	LDA #0
	STA SDMCTL; TURN ANTIC OFF FOR A MOMENT ...
	LDA #HLIST; WHILE WE STORE OUR NEW LIST'S ADDRESS
	STA SDLSTL; IN THE OS DISPLAY POINTER.
	LDA # HLIST/256; NOW FOR THE HIGH BYTE.
	STA SDLSTH; NOW ANTIC WILL KNOW OUR NEW ADDRESS
	LDA #$22
	STA SDMCTL; ... SO WE'LL TURN ANTIC BACK ON NOW
	;
	FINI
	RTS